/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiWebBrowseRouteImport } from './routes/api/web-browse'
import { Route as ApiChatAnthropicRouteImport } from './routes/api/chat/anthropic'
import { Route as ApiChatGoogleRouteImport } from './routes/api/chat/google'
import { Route as ApiChatGrokRouteImport } from './routes/api/chat/grok'
import { Route as ApiChatOpenaiRouteImport } from './routes/api/chat/openai'
import { Route as ApiChatStatusRouteImport } from './routes/api/chat/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebBrowseRoute = ApiWebBrowseRouteImport.update({
  id: '/api/web-browse',
  path: '/api/web-browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAnthropicRoute = ApiChatAnthropicRouteImport.update({
  id: '/api/chat/anthropic',
  path: '/api/chat/anthropic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatGoogleRoute = ApiChatGoogleRouteImport.update({
  id: '/api/chat/google',
  path: '/api/chat/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatGrokRoute = ApiChatGrokRouteImport.update({
  id: '/api/chat/grok',
  path: '/api/chat/grok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatOpenaiRoute = ApiChatOpenaiRouteImport.update({
  id: '/api/chat/openai',
  path: '/api/chat/openai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStatusRoute = ApiChatStatusRouteImport.update({
  id: '/api/chat/status',
  path: '/api/chat/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/privacy': typeof PrivacyRoute
  '/api/web-browse': typeof ApiWebBrowseRoute
  '/api/chat/anthropic': typeof ApiChatAnthropicRoute
  '/api/chat/google': typeof ApiChatGoogleRoute
  '/api/chat/grok': typeof ApiChatGrokRoute
  '/api/chat/openai': typeof ApiChatOpenaiRoute
  '/api/chat/status': typeof ApiChatStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/privacy': typeof PrivacyRoute
  '/api/web-browse': typeof ApiWebBrowseRoute
  '/api/chat/anthropic': typeof ApiChatAnthropicRoute
  '/api/chat/google': typeof ApiChatGoogleRoute
  '/api/chat/grok': typeof ApiChatGrokRoute
  '/api/chat/openai': typeof ApiChatOpenaiRoute
  '/api/chat/status': typeof ApiChatStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/privacy': typeof PrivacyRoute
  '/api/web-browse': typeof ApiWebBrowseRoute
  '/api/chat/anthropic': typeof ApiChatAnthropicRoute
  '/api/chat/google': typeof ApiChatGoogleRoute
  '/api/chat/grok': typeof ApiChatGrokRoute
  '/api/chat/openai': typeof ApiChatOpenaiRoute
  '/api/chat/status': typeof ApiChatStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/privacy'
    | '/api/web-browse'
    | '/api/chat/anthropic'
    | '/api/chat/google'
    | '/api/chat/grok'
    | '/api/chat/openai'
    | '/api/chat/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/privacy'
    | '/api/web-browse'
    | '/api/chat/anthropic'
    | '/api/chat/google'
    | '/api/chat/grok'
    | '/api/chat/openai'
    | '/api/chat/status'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/privacy'
    | '/api/web-browse'
    | '/api/chat/anthropic'
    | '/api/chat/google'
    | '/api/chat/grok'
    | '/api/chat/openai'
    | '/api/chat/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiWebBrowseRoute: typeof ApiWebBrowseRoute
  ApiChatAnthropicRoute: typeof ApiChatAnthropicRoute
  ApiChatGoogleRoute: typeof ApiChatGoogleRoute
  ApiChatGrokRoute: typeof ApiChatGrokRoute
  ApiChatOpenaiRoute: typeof ApiChatOpenaiRoute
  ApiChatStatusRoute: typeof ApiChatStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-browse': {
      id: '/api/web-browse'
      path: '/api/web-browse'
      fullPath: '/api/web-browse'
      preLoaderRoute: typeof ApiWebBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/anthropic': {
      id: '/api/chat/anthropic'
      path: '/api/chat/anthropic'
      fullPath: '/api/chat/anthropic'
      preLoaderRoute: typeof ApiChatAnthropicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/google': {
      id: '/api/chat/google'
      path: '/api/chat/google'
      fullPath: '/api/chat/google'
      preLoaderRoute: typeof ApiChatGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/grok': {
      id: '/api/chat/grok'
      path: '/api/chat/grok'
      fullPath: '/api/chat/grok'
      preLoaderRoute: typeof ApiChatGrokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/openai': {
      id: '/api/chat/openai'
      path: '/api/chat/openai'
      fullPath: '/api/chat/openai'
      preLoaderRoute: typeof ApiChatOpenaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/status': {
      id: '/api/chat/status'
      path: '/api/chat/status'
      fullPath: '/api/chat/status'
      preLoaderRoute: typeof ApiChatStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  PrivacyRoute: PrivacyRoute,
  ApiWebBrowseRoute: ApiWebBrowseRoute,
  ApiChatAnthropicRoute: ApiChatAnthropicRoute,
  ApiChatGoogleRoute: ApiChatGoogleRoute,
  ApiChatGrokRoute: ApiChatGrokRoute,
  ApiChatOpenaiRoute: ApiChatOpenaiRoute,
  ApiChatStatusRoute: ApiChatStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
